### PR TITLE
Server Knights v0.8 - Custom Skins & Emotes during Multiplay

### PR DESCRIPTION
**Pull request by PrashantMohta**
- Adds Skin Syncing across clients
- Server Defined Skins
- Skin Meta data Support
- covers Knight.png - player character, slashes , nail Arts , dash & Cdash & thorns of agony
- covers Sprint.png - dream nail , sprint master
- Keys 0-9 Above Alphabets Select the Skin

Further Info regarding Installation & creating custom skins [Custom Skin flow document](https://docs.google.com/document/d/1PxgBK2qzm6e6Ev3u0lKE_rx-jS0O5OlcKhKC112KGyk/edit)

- Adds Emotes (5 from Royalty-free set by [Kenney.nl](https://www.kenney.nl/))
- Keyboard -> G,H,J,K,L 
- Controller -> Right Stick

- all keybindings are re-mappable using binding.json (we would need to include this with release)

### CODE REVIEW

**Comment by Extremelyd1** [comment]
@PrashantMohta Could you please provide a breakdown of how the system you implemented works. This would help in addition to the already given bullet points that list features.
It also seems most (if not all) of the files you contributed are devoid of any comments. Together with the fact that there are 87 files in the PR this makes it entirely infeasible to review.

**Comment by PrashantMohta** [comment]
> @PrashantMohta Could you please provide a breakdown of how the system you implemented works. This would help in addition to the already given bullet points that list features.
> It also seems most (if not all) of the files you contributed are devoid of any comments. Together with the fact that there are 87 files in the PR this makes it entirely infeasible to review.

sure , majority of the files are the effect Animations which are either unchanged apart from the function signature or addition of a single function that is `updateTextureInMaterialPropertyBlock` which adds a MaterialPropertyBlock to the GO to replace the texture. there's also the 5 emote assets.  I'll skip all these files in the breakdown (they're 63 / 87). 

I am also assuming that, the part where we send and receive packets and the classes for the new packets are self explanatory to you, but in brief : 

We have added 2 new types of packets "session" & "update" for server knight, The session packet is sent to client on receiving serverHello and informs it of the skins available in this game session. The update packet informs the client about any skin / emote events. "skin" is a new property of playerData similar to "team" this means majority of the packet send and receive code is identical to it. emote is a one off event that is simply used to show an emote. 

This brings us to the 5 core files where majority of the new logic resides.

AnimationManager.cs , Serverknights.cs , SkinLoader.cs , SkinManager.cs , EmoteManager.cs 

In AnimationManager.cs , before playing an animation on the player character, we check if that clip uses sprites from Sprint.png or Knight.png & `updateTextureInMaterialPropertyBlock` accordingly. and onHeroUpdate we set a boolean in serverknights to let it know if we are in connected state or not.

 Serverknights.cs - does the job of exposing skinManager and emoteManager to the rest of the code, certain things like player Input onHeroUpdate & Reacting to server connect / disconnect that needed to be handled in both of them are handled here. 
 
 SkinManager.cs &  SkinLoader.cs 
 They're the core of loading and switching skins. 
 At game load, we load keybindings from bindings.json. getServerJson  &  clientSetSession support the transfer of server.json.
 & once player is connected & clientSession is set on next hero update we load the skin files using SkinLoader. 
 we keep an array to map our skin number to skin id (0-9) => ('hashed<contenthash>').
 
 loadSkins in SkinLoader then checks if the directory with that skin id is present and if so loads the skin's skin.json , Knight.png & Sprint.png, the png files are only loaded if defined in skin.json & present on disk. once a skin is loaded, any missing textures are patched from the default skin & this new clientSkin is added into 'KnightMap' which is a map of skinId to clientSkin.

on pressing a key we just change the skin of the local player and sent an update to the server, which then updates all clients, on receiving a skin update from remote player, we just replace their playerData.Skin with the new skin number. (the skinsArray & KnightMap will be used to render it during Animation)

EmoteManager.cs 

on game start, we read bindings.json to define keyboard keymapping, we also load emotes from the assembly resources.
after connect we listen for player input onHeroUpdate,
For keyboard a key press shows the emote by pulling it from our pool of 25 emote GOs. 
For controller , we segment the 360degs into 6 where 5 sectors will show an emote and 1 will cancel. On pressing and dragging the right stick along the edge it will show a scaled down UI of the emote to allow the player to pick their emote. on release this emote will be shown.
If selected, an emote will be displayed locally & it's id (0-5) will be sent to the server & thus to the remote players via an update event, based on the id in the update event we will spawn a new emote on the sending player.
 
we also ensure that players can't spam emotes too frequently to avoid the UI breaking entirely.

EmoteScript - this is a monobehaviour that we attach on Emote GOs, this fades, scales and translates the emote & keeps it on top of the player even if they move, before setting the GO inactive once the time is up.

**Comment by Extremelyd1** [comment]
There's a lot of the PR that I simply can't review due to its size. Therefore, I'm opting to merge this for now, gradually review and handle the changed code on master. I've written a contribution document that will be pushed to master containing the necessary steps to avoid this in the future.

**Comment by PrashantMohta** [comment]
sure thing!

**Pull request merged**
